develop_config = {
    "environment": "develop",
    "mongo_connection_string": "mongodb://mongo/ertis_auth_test_db",
    "api_version": "v1",
    "application_secret": "AtqVaL11EHVPEpbu2mr0yZgKXj1BnRj0",
    "default_database": "ertis_auth_test_db",
    "verify_token": True,
    "error_handler": True,
    "debug": True,
    "host": "0.0.0.0",
    "port": 8888,
    "sentry_activate": True,
    "sentry_connection_string": 'https://980942d55f844141970f0b94df545da1@o375302.ingest.sentry.io/5194488?verify_ssl=0',
    "google_oauth2_url": "https://accounts.google.com/o/oauth2",
    "google_token_validator_url": "https://oauth2.googleapis.com/tokeninfo",
    "facebook_graph_api_url": "https://graph.facebook.com/v6.0",
    "mail_activate": False,
    "mail_server": "smtp.googlemail.com",
    "mail_port": 465,
    "mail_username": "",
    "mail_password": "",
    "mail_use_tls": False,
    "mail_use_ssl": True,
    "major_version": 2,
    "minor_version": 1,
    "patch_version": 0,
    "version": "2.1.0"
}
